### PR TITLE
PATCH: fix non-existing class Swift_Mime_Message

### PR DESCRIPTION
**Pull request by sunnysideup**
see: https://github.com/swiftmailer/swiftmailer/blob/master/CHANGES#L111-L112

### CODE REVIEW

**Comment by flashbackzoo** [comment]
I'm having this problem too. @sunnysideup I see you removed the type, the correct one to use is `Swift_Mime_SimpleMessage`

**Comment by aletail** [comment]
Same issue here, occurs on any silverstripe version higher then 4.8

**Comment by unclecheese** [comment]
Thank you!!!

**Comment by unclecheese** [comment]
Only merged because it affected me. I'm killing it at OS.

**Pull request merged**
